name-template: 'Release $NEXT_PATCH_VERSION 🚀'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    label: 'feature'
  - title: '🐛 Bug Fixes'
    label: 'bug'
  - title: '🧪 Tests'
    label: 'test'
template: |
  ## Changes Since Last Release

  ### 🚀 Features
  $CHANGES_BY_CATEGORY

  ### 🐛 Bug Fixes
  $CHANGES_BY_CATEGORY

  ### 🔧 Other Changes
  $CHANGES_BY_CATEGORY
