services:
  server:
    ports: !reset []
    expose:
      - 3000
    networks:
      - traefik
      - feedfathom
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.feedfathom.rule=Host(`${FEED_FATHOM_DOMAIN}`)"
      - "traefik.http.routers.feedfathom.entrypoints=web"
      - "traefik.http.services.feedfathom.loadbalancer.server.port=3000"

  mail:
    networks:
      - traefik
      - feedfathom
    ports: !reset []
    expose:
      - 25
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.mail-tcp.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.mail-tcp.entrypoints=smtp"
      - "traefik.tcp.services.mail-tcp.loadbalancer.server.port=25"

networks:
  traefik:
    external: true
  feedfathom:
