services:
  server:
    ports: !reset []
    expose:
      - 3000
    networks:
      - traefik
      - feedfathom
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.feedfathom.rule=Host(`${FEED_FATHOM_DOMAIN}`)"
      - "traefik.http.routers.feedfathom.entrypoints=web"
  mail:
    networks:
      - traefik
      - feedfathom
    ports: !reset []
    expose:
      - 25
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.smtp.rule=Host(`*`)"
      - "traefik.tcp.routers.smtp.entrypoints=smtp"

networks:
  traefik:
    external: true
  feedfathom:
