services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    user: "${_UID}:${_GID}"
    volumes:
      - ./:/app/
    command: ["run", "watch-server"]
    environment:
      - ENABLE_REGISTRATION=true
      - BROWSER=none
      - FEED_FATHOM_DOMAIN=localhost:3456
      - MAILJET_API_KEY=
      - MAILJET_API_SECRET=
      - TURNSTILE_SITE_KEY=
      - TURNSTILE_SECRET_KEY=
    ports:
      - "3456:5173"

  migrator:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    user: "${_UID}:${_GID}"
    volumes:
      - ./:/app/
    command: ["run", "watch-worker"]

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    user: "${_UID}:${_GID}"
    volumes:
      - ./:/app/
    command: ["run", "watch-worker"]
    deploy:
      replicas: 1

  mail:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    user: "${_UID}:${_GID}"
    volumes:
      - ./:/app/
    command: ["run", "watch-worker"]
