services:
  server:
    extends:
      file: docker-compose.yml
      service: server
    ports: []
    networks:
      - traefik
      - feedfathom
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.feedfathom.rule=Host(`${FEED_FATHOM_DOMAIN}`)"
      - "traefik.http.routers.feedfathom.entrypoints=web"
      - "traefik.http.services.feedfathom.loadbalancer.server.port=3000"

networks:
  traefik:
    external: true
  feedfathom:
