services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    user: "${_UID}:${_GID}"
    volumes:
      - ./:/app/
    command: ["run", "watch-server"]
    environment:
      - ENABLE_REGISTRATION=true
    ports:
      - 5173:5173

  migrator:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    user: "${_UID}:${_GID}"
    volumes:
      - ./:/app/
    command: ["run", "watch-worker"]

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    user: "${_UID}:${_GID}"
    volumes:
      - ./:/app/
    command: ["run", "watch-worker"]
    deploy:
      replicas: 1

  mail:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    user: "${_UID}:${_GID}"
    volumes:
      - ./:/app/
    command: ["run", "watch-worker"]
