services:
  redis:
    image: "redis"
    restart: always
    command: redis-server --appendonly yes
    healthcheck:
      test: "redis-cli ping | grep PONG || exit 1"
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - redis_storage:/data
    networks:
      - feedfathom

  postgres:
    image: "pgautoupgrade/pgautoupgrade:17-bookworm"
    restart: always
    command: [ "-c", "max_connections=1000" ]
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
    healthcheck:
      test: 'pg_isready --username=${POSTGRES_USER:-postgres} && psql --username=${POSTGRES_USER:-postgres} -c "SELECT * FROM postgres.pg_catalog.pg_database;"'
      interval: 1s
      timeout: 1s
      retries: 25
      start_period: 1s
    volumes:
      - postgres_storage_17:/var/lib/postgresql/data
    networks:
      - feedfathom

  migrator:
    init: true
    image: ghcr.io/smartrss/feedfathom/feedfathom-worker:${FEEDFATHOM_TAG:-main}
    environment:
      INTEGRATION: "migrator"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - feedfathom

  server:
    init: true
    image: ghcr.io/smartrss/feedfathom/feedfathom-server:${FEEDFATHOM_TAG:-main}
    restart: always
    deploy:
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      replicas: ${APP_REPLICAS:-1}
    ports:
      - "3456:3000"
    environment:
      ALLOWED_EMAILS: ${ALLOWED_EMAILS:-}
      ENABLE_REGISTRATION: ${ENABLE_REGISTRATION:-false}
      MAIL_REPLICAS: ${MAIL_REPLICAS:-0}
      MAIL_ENABLED: ${MAIL_ENABLED:-false}
      FEED_FATHOM_DOMAIN: ${FEED_FATHOM_DOMAIN:-}
      MAILJET_API_KEY: ${MAILJET_API_KEY}
      MAILJET_API_SECRET: ${MAILJET_API_SECRET}
      TURNSTILE_SITE_KEY: ${TURNSTILE_SITE_KEY}
      TURNSTILE_SECRET_KEY: ${TURNSTILE_SECRET_KEY}
    healthcheck:
      test: "curl -f http://localhost:3000/healthcheck || exit 1"
      interval: 5s
      timeout: 1s
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    tmpfs:
      - /tmp
    networks:
      - feedfathom

  worker:
    init: true
    image: ghcr.io/smartrss/feedfathom/feedfathom-worker:${FEEDFATHOM_TAG:-main}
    restart: always
    environment:
      DEBUG: bull:*
      INTEGRATION: worker
      WORKER_CONCURRENCY: ${WORKER_CONCURRENCY:-25}
      LOCK_DURATION: ${LOCK_DURATION:-60}
      CLEANUP_INTERVAL: ${CLEANUP_INTERVAL:-20}
      GATHER_JOBS_INTERVAL: ${GATHER_JOBS_INTERVAL:-20}
    deploy:
      replicas: ${WORKER_REPLICAS:-10}
      resources:
        limits:
          cpus: "${WORKER_CPU_LIMIT:-0.50}"
          memory: "${WORKER_MEM_LIMIT:-1500M}"
        reservations:
          cpus: "${WORKER_CPU_RESERVATION:-0.25}"
          memory: "${WORKER_MEM_RESERVATION:-500M}"
      update_config:
        parallelism: 5
        delay: 15s
        order: start-first
        failure_action: rollback
        monitor: 15s
    healthcheck:
      test: "curl -f http://localhost:3000/healthcheck || exit 1"
      interval: 5s
      timeout: 1s
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    tmpfs:
      - /tmp
    networks:
      - feedfathom

  mail:
    init: true
    image: ghcr.io/smartrss/feedfathom/feedfathom-worker:${FEEDFATHOM_TAG:-main}
    ports:
      - "25:25"
    restart: always
    environment:
      DEBUG: bull:*
      INTEGRATION: "mail"
    deploy:
      mode: global
      replicas: ${MAIL_REPLICAS:-0}
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
    healthcheck:
      test: "curl -f http://localhost:3000/healthcheck || exit 1"
      interval: 5s
      timeout: 1s
    depends_on:
      postgres:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    tmpfs:
      - /tmp
    networks:
      - feedfathom

volumes:
  redis_storage:
    driver: local
  postgres_storage_17:
    driver: local

networks:
  feedfathom:
    driver: bridge
