-- Migration 0024 added sources.kind with DEFAULT 'feed' and no backfill, so
-- every pre-existing row became 'feed' -- including email sources. The
-- `url LIKE 'http%'` heuristic that `kind` replaced had classified those
-- correctly, so swapping the heuristic for a column silently lost the
-- distinction it encoded. The affected rows have been failing every poll
-- since ("<address> cannot be parsed as a URL"), because there is no HTTP
-- endpoint behind an email address to fetch.
--
-- Same shape as the heuristic being restored: an email source's url is the
-- delivery address, never an http(s) URL. New sources are unaffected --
-- the subscribe route has always set kind explicitly.
UPDATE "sources" SET "kind" = 'email' WHERE "url" NOT LIKE 'http%';
