export enum JobName {
  PARSE_SOURCE = "parseSource",
  GATHER_JOBS = "gatherJobs",
  CLEANUP = "cleanup",
  SINGLETON_TEST_JOB = "SINGLETON:TEST_JOB",
  SINGLETON_ANOTHER_TEST = "SINGLETON:ANOTHER_TEST",
}
