name: Branch Up-to-date

on: [pull_request]

jobs:
  branch-up-to-date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if branch is behind main
        run: |
          git fetch origin main
          BEHIND_COUNT=$(git rev-list --count HEAD..origin/main)
          if [ "$BEHIND_COUNT" -gt "0" ]; then
            echo "::error::Branch is behind main by $BEHIND_COUNT commits. Please update your branch."
            exit 1
          fi
