name: Lint

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  lint:
    name: Project Lint
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write
      checks: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun Runtime
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          
      - name: Install Dependencies
        run: bun install --frozen-lockfile
        
      - name: Run Lint
        id: lint
        uses: actions/github-script@v7
        with:
          script: |
            try {
              await exec.exec('bun run lint')
              await github.rest.checks.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: 'lint',
                head_sha: context.sha,
                status: 'completed',
                conclusion: 'success',
                output: {
                  title: 'Lint Results',
                  summary: 'All lint checks passed successfully'
                }
              })
            } catch (error) {
              await github.rest.checks.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: 'lint',
                head_sha: context.sha,
                status: 'completed',
                conclusion: 'failure',
                output: {
                  title: 'Lint Results',
                  summary: 'Lint checks failed',
                  text: error.message
                }
              })
              throw error
            } 