name: Quality Checks

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: SvelteKit sync
        run: bun svelte-kit sync
      - name: Run tests
        run: bun test
      - name: Run Biome check
        run: bun biome check
      - name: Run TypeScript checks
        run: bun tsgo
      - name: Run Svelte check
        run: bun svelte-check
      - name: Run Knip
        run: bun knip
      - name: Run ESLint
        run: bun eslint
